#!/bin/bash

# Whether to do SLURM configs or not
slurm=0

# Prints usage
print_usage() {
    cat << EOF
usage: ./setup [-h] [-s]

options:
    -h, --help      show brief help and exit
    -s, --slurm     whether to configure SLURM related files/configs/options 
EOF
}

# Copys the file if it exists
copy_if_exists() {
    if [ -f $1 ]; then
        mv $1 "$1_old"
    fi
}

if [ $# -eq 1 ]; then
    case $1 in
        -h|--help)
            cat << EOF
setup - Helpful setup script to link dot files
        (and optionally create them for SLURM cluster use).

EOF
            print_usage
            exit 0
            ;;
        -s|--slurm)
            slurm=1
            ;;
        *)
            print_usage
            exit 1
            ;;
    esac
elif [ $# -gt 1 ]; then
    print_usage
    exit 1
fi

# Do slurm config
if [ $slurm -eq 1 ]; then

# Read in which shell is being used
read -p "Shell: [bash] " shell
# Have a default shell of bash
shell=${shell:-bash}

# Read in username to use in expanding .envs and .bash_aliases_template
read -p "Username: [gzwei] " USERNAME
# Have a default username of gzwei
USERNAME=${USERNAME:-gzwei}

# Specify a working directory
read -p "Work directory: " WORK
# Expand tilde
WORK="${WORK/#\~/$HOME}"

# There needs to be a valid working directory
while [ -z "$WORK" -o "$WORK" == " " -o ! -d "$WORK" ]; do
    read -p "Please provide a valid path to your working directory: " WORK
    WORK="${WORK/#\~/$HOME}"
done

# Specify a scratch directory
read -p "Scratch directory: " SCRATCH
# Expand tilde
SCRATCH="${SCRATCH/#\~/$HOME}"

# There needs to be a valid scratch directory
while [ -z "$SCRATCH" -o "$SCRATCH" == " " -o ! -d "$SCRATCH" ]; do
    read -p "Please provide a valid path to your scratch directory: " SCRATCH
    SCRATCH="${SCRATCH/#\~/$HOME}"
done

# Create .envs
eval "echo \"$(cat templates/.envs_template)\"" > .envs
# Create .aliases
eval "echo \"$(cat templates/.aliases_template)\"" > .aliases

# Add environment variable definitions
if ! grep -q ".envs" ~/".${shell}rc"; then
tee -a ~/".${shell}rc" << EOF
# Environment variable definitions.
if [ -f ~/.envs ]; then
    . ~/.envs
fi
EOF
fi

# Add shell alias definitions
if ! grep -q ".${shell}_aliases" ~/".${shell}rc"; then
tee -a ~/".${shell}rc" << EOF
# Alias definitions.
if [ -f ~/".${shell}_aliases" ]; then
    . ~/".${shell}_aliases"
fi
EOF
fi

# Copy old .envs and shell aliases just in case
copy_if_exists ~/.envs
copy_if_exists ~/".${shell}_aliases"

# Create the symbolic links for each file
ln -s "$PWD/.envs" ~/.envs
ln -s "$PWD/.aliases" ~/".${shell}_aliases"

fi

# Copy old .inputrc and .vimrc just in case
copy_if_exists ~/.inputrc
copy_if_exists ~/.vimrc

# Link the .inputrc and .vimrc regardless
ln -s "$PWD/.inputrc" ~/.inputrc
ln -s "$PWD/.vimrc" ~/.vimrc

# Make sure TMPDIR is created
mkdir -p $SCRATCH/tmp

echo "Done with setup!"
