-- Setup all plugins
require("user.plugins-setup")
-- Core configurations
require("user.core.colorscheme")
require("user.core.options")
require("user.core.keymaps")
-- All plugin configurations
require("user.plugins.autopairs")
require("user.plugins.barbar")
require("user.plugins.comment")
require("user.plugins.gitsigns")
require("user.plugins.indent-blankline")
require("user.plugins.lsp")
require("user.plugins.lualine")
require("user.plugins.nvim-cmp")
require("user.plugins.nvim-tree")
require("user.plugins.tabout")
require("user.plugins.telescope")
require("user.plugins.toggleterm")
require("user.plugins.treesitter")
